[package]
name = "rust-uniswap-task"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tokio = "1.21.2"
hex = "0.4.3"
ethers = { version = "2.0.0", features = ["abigen", "rustls", "ws"]}
